http:
  routers:
    echo:
      rule: "Path(`/echo`)"
      entryPoints:
        - web
      service: echo-svc

    cookie:
      rule: "Path(`/cookie`)"
      entryPoints:
        - web
      service: echo-svc

    catchall:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: echo-svc

  services:
    echo-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9090"
